version: "3"

services:
  postgres:
    image: postgis/postgis:17-3.4-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data